version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go build -o sizeof
  test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go test ./...
  release:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: go build -o sizeof
      - run:
          name: Install release tools
          command: |
            curl -fL https://github.com/goreleaser/goreleaser/releases/latest/download/goreleaser_Linux_x86_64.tar.gz | tar -xz
            sudo mv goreleaser /usr/local/bin/
      - run: goreleaser release --rm-dist --skip-publish
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)?$/
